/*
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.niste15.mdsd.android.ui.internal.AndroidActivator;

public class AndroidUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AndroidActivator.getInstance().getInjector("org.xtext.niste15.mdsd.Android");
	}

}
