/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.niste15.mdsd.android.AndroidFactory
 * @model kind="package"
 * @generated
 */
public interface AndroidPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "android";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/niste15/mdsd/Android";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "android";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AndroidPackage eINSTANCE = org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ModelImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Application</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__APPLICATION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ApplicationImpl <em>Application</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ApplicationImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getApplication()
   * @generated
   */
  int APPLICATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Panes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__PANES = 1;

  /**
   * The number of structural features of the '<em>Application</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.PaneImpl <em>Pane</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.PaneImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getPane()
   * @generated
   */
  int PANE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANE__NAME = 0;

  /**
   * The feature id for the '<em><b>Frames</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANE__FRAMES = 1;

  /**
   * The number of structural features of the '<em>Pane</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.FrameImpl <em>Frame</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.FrameImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getFrame()
   * @generated
   */
  int FRAME = 3;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Frame</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ElementsImpl <em>Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ElementsImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getElements()
   * @generated
   */
  int ELEMENTS = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS__TEXT = 0;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS__CONSTRAINT = 1;

  /**
   * The number of structural features of the '<em>Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.TextImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getText()
   * @generated
   */
  int TEXT = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__TEXT = ELEMENTS__TEXT;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__CONSTRAINT = ELEMENTS__CONSTRAINT;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ButtonImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 6;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TEXT = ELEMENTS__TEXT;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__CONSTRAINT = ELEMENTS__CONSTRAINT;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ConstraintImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 7;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintTypeVerticalImpl <em>Constraint Type Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ConstraintTypeVerticalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintTypeVertical()
   * @generated
   */
  int CONSTRAINT_TYPE_VERTICAL = 8;

  /**
   * The number of structural features of the '<em>Constraint Type Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_TYPE_VERTICAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintTypeHorizontalImpl <em>Constraint Type Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ConstraintTypeHorizontalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintTypeHorizontal()
   * @generated
   */
  int CONSTRAINT_TYPE_HORIZONTAL = 9;

  /**
   * The number of structural features of the '<em>Constraint Type Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_TYPE_HORIZONTAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintParameterVerticalImpl <em>Constraint Parameter Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ConstraintParameterVerticalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintParameterVertical()
   * @generated
   */
  int CONSTRAINT_PARAMETER_VERTICAL = 10;

  /**
   * The number of structural features of the '<em>Constraint Parameter Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintParameterHorizontalImpl <em>Constraint Parameter Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.ConstraintParameterHorizontalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintParameterHorizontal()
   * @generated
   */
  int CONSTRAINT_PARAMETER_HORIZONTAL = 11;

  /**
   * The number of structural features of the '<em>Constraint Parameter Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_PARAMETER_HORIZONTAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.VerticalImpl <em>Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.VerticalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getVertical()
   * @generated
   */
  int VERTICAL = 12;

  /**
   * The feature id for the '<em><b>Constraint Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL__CONSTRAINT_TYPE = CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL__PARAM = CONSTRAINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_FEATURE_COUNT = CONSTRAINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.HorizontalImpl <em>Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.HorizontalImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getHorizontal()
   * @generated
   */
  int HORIZONTAL = 13;

  /**
   * The feature id for the '<em><b>Constraint Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL__CONSTRAINT_TYPE = CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL__PARAM = CONSTRAINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_FEATURE_COUNT = CONSTRAINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.RightOfImpl <em>Right Of</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.RightOfImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getRightOf()
   * @generated
   */
  int RIGHT_OF = 14;

  /**
   * The number of structural features of the '<em>Right Of</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_OF_FEATURE_COUNT = CONSTRAINT_TYPE_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.LeftOfImpl <em>Left Of</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.LeftOfImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getLeftOf()
   * @generated
   */
  int LEFT_OF = 15;

  /**
   * The number of structural features of the '<em>Left Of</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_OF_FEATURE_COUNT = CONSTRAINT_TYPE_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.BottomOfImpl <em>Bottom Of</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.BottomOfImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getBottomOf()
   * @generated
   */
  int BOTTOM_OF = 16;

  /**
   * The number of structural features of the '<em>Bottom Of</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTTOM_OF_FEATURE_COUNT = CONSTRAINT_TYPE_HORIZONTAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.TopOfImpl <em>Top Of</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.TopOfImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getTopOf()
   * @generated
   */
  int TOP_OF = 17;

  /**
   * The number of structural features of the '<em>Top Of</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_OF_FEATURE_COUNT = CONSTRAINT_TYPE_HORIZONTAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.PersentageImpl <em>Persentage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.PersentageImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getPersentage()
   * @generated
   */
  int PERSENTAGE = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSENTAGE__VALUE = CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Persentage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSENTAGE_FEATURE_COUNT = CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.RightImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getRight()
   * @generated
   */
  int RIGHT = 19;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.LeftImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getLeft()
   * @generated
   */
  int LEFT = 20;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.MiddleImpl <em>Middle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.MiddleImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getMiddle()
   * @generated
   */
  int MIDDLE = 21;

  /**
   * The number of structural features of the '<em>Middle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIDDLE_FEATURE_COUNT = CONSTRAINT_PARAMETER_VERTICAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.TopImpl <em>Top</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.TopImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getTop()
   * @generated
   */
  int TOP = 22;

  /**
   * The number of structural features of the '<em>Top</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_FEATURE_COUNT = CONSTRAINT_PARAMETER_HORIZONTAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.niste15.mdsd.android.impl.BottomImpl <em>Bottom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.niste15.mdsd.android.impl.BottomImpl
   * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getBottom()
   * @generated
   */
  int BOTTOM = 23;

  /**
   * The number of structural features of the '<em>Bottom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOTTOM_FEATURE_COUNT = CONSTRAINT_PARAMETER_HORIZONTAL_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.niste15.mdsd.android.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.niste15.mdsd.android.Model#getApplication <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Application</em>'.
   * @see org.xtext.niste15.mdsd.android.Model#getApplication()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Application();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Application <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application</em>'.
   * @see org.xtext.niste15.mdsd.android.Application
   * @generated
   */
  EClass getApplication();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.niste15.mdsd.android.Application#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.niste15.mdsd.android.Application#getName()
   * @see #getApplication()
   * @generated
   */
  EAttribute getApplication_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.niste15.mdsd.android.Application#getPanes <em>Panes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Panes</em>'.
   * @see org.xtext.niste15.mdsd.android.Application#getPanes()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Panes();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Pane <em>Pane</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pane</em>'.
   * @see org.xtext.niste15.mdsd.android.Pane
   * @generated
   */
  EClass getPane();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.niste15.mdsd.android.Pane#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.niste15.mdsd.android.Pane#getName()
   * @see #getPane()
   * @generated
   */
  EAttribute getPane_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.niste15.mdsd.android.Pane#getFrames <em>Frames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Frames</em>'.
   * @see org.xtext.niste15.mdsd.android.Pane#getFrames()
   * @see #getPane()
   * @generated
   */
  EReference getPane_Frames();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Frame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame</em>'.
   * @see org.xtext.niste15.mdsd.android.Frame
   * @generated
   */
  EClass getFrame();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.niste15.mdsd.android.Frame#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.niste15.mdsd.android.Frame#getElements()
   * @see #getFrame()
   * @generated
   */
  EReference getFrame_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Elements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elements</em>'.
   * @see org.xtext.niste15.mdsd.android.Elements
   * @generated
   */
  EClass getElements();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.niste15.mdsd.android.Elements#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.niste15.mdsd.android.Elements#getText()
   * @see #getElements()
   * @generated
   */
  EAttribute getElements_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.niste15.mdsd.android.Elements#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint</em>'.
   * @see org.xtext.niste15.mdsd.android.Elements#getConstraint()
   * @see #getElements()
   * @generated
   */
  EReference getElements_Constraint();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see org.xtext.niste15.mdsd.android.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.xtext.niste15.mdsd.android.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see org.xtext.niste15.mdsd.android.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.ConstraintTypeVertical <em>Constraint Type Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint Type Vertical</em>'.
   * @see org.xtext.niste15.mdsd.android.ConstraintTypeVertical
   * @generated
   */
  EClass getConstraintTypeVertical();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.ConstraintTypeHorizontal <em>Constraint Type Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint Type Horizontal</em>'.
   * @see org.xtext.niste15.mdsd.android.ConstraintTypeHorizontal
   * @generated
   */
  EClass getConstraintTypeHorizontal();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.ConstraintParameterVertical <em>Constraint Parameter Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint Parameter Vertical</em>'.
   * @see org.xtext.niste15.mdsd.android.ConstraintParameterVertical
   * @generated
   */
  EClass getConstraintParameterVertical();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.ConstraintParameterHorizontal <em>Constraint Parameter Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint Parameter Horizontal</em>'.
   * @see org.xtext.niste15.mdsd.android.ConstraintParameterHorizontal
   * @generated
   */
  EClass getConstraintParameterHorizontal();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Vertical <em>Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertical</em>'.
   * @see org.xtext.niste15.mdsd.android.Vertical
   * @generated
   */
  EClass getVertical();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.niste15.mdsd.android.Vertical#getConstraintType <em>Constraint Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint Type</em>'.
   * @see org.xtext.niste15.mdsd.android.Vertical#getConstraintType()
   * @see #getVertical()
   * @generated
   */
  EReference getVertical_ConstraintType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.niste15.mdsd.android.Vertical#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param</em>'.
   * @see org.xtext.niste15.mdsd.android.Vertical#getParam()
   * @see #getVertical()
   * @generated
   */
  EReference getVertical_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Horizontal <em>Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Horizontal</em>'.
   * @see org.xtext.niste15.mdsd.android.Horizontal
   * @generated
   */
  EClass getHorizontal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.niste15.mdsd.android.Horizontal#getConstraintType <em>Constraint Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint Type</em>'.
   * @see org.xtext.niste15.mdsd.android.Horizontal#getConstraintType()
   * @see #getHorizontal()
   * @generated
   */
  EReference getHorizontal_ConstraintType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.niste15.mdsd.android.Horizontal#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param</em>'.
   * @see org.xtext.niste15.mdsd.android.Horizontal#getParam()
   * @see #getHorizontal()
   * @generated
   */
  EReference getHorizontal_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.RightOf <em>Right Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right Of</em>'.
   * @see org.xtext.niste15.mdsd.android.RightOf
   * @generated
   */
  EClass getRightOf();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.LeftOf <em>Left Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left Of</em>'.
   * @see org.xtext.niste15.mdsd.android.LeftOf
   * @generated
   */
  EClass getLeftOf();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.BottomOf <em>Bottom Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bottom Of</em>'.
   * @see org.xtext.niste15.mdsd.android.BottomOf
   * @generated
   */
  EClass getBottomOf();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.TopOf <em>Top Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Of</em>'.
   * @see org.xtext.niste15.mdsd.android.TopOf
   * @generated
   */
  EClass getTopOf();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Persentage <em>Persentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Persentage</em>'.
   * @see org.xtext.niste15.mdsd.android.Persentage
   * @generated
   */
  EClass getPersentage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.niste15.mdsd.android.Persentage#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.niste15.mdsd.android.Persentage#getValue()
   * @see #getPersentage()
   * @generated
   */
  EAttribute getPersentage_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see org.xtext.niste15.mdsd.android.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see org.xtext.niste15.mdsd.android.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Middle <em>Middle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Middle</em>'.
   * @see org.xtext.niste15.mdsd.android.Middle
   * @generated
   */
  EClass getMiddle();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Top <em>Top</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top</em>'.
   * @see org.xtext.niste15.mdsd.android.Top
   * @generated
   */
  EClass getTop();

  /**
   * Returns the meta object for class '{@link org.xtext.niste15.mdsd.android.Bottom <em>Bottom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bottom</em>'.
   * @see org.xtext.niste15.mdsd.android.Bottom
   * @generated
   */
  EClass getBottom();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AndroidFactory getAndroidFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ModelImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Application</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__APPLICATION = eINSTANCE.getModel_Application();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ApplicationImpl <em>Application</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ApplicationImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getApplication()
     * @generated
     */
    EClass APPLICATION = eINSTANCE.getApplication();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION__NAME = eINSTANCE.getApplication_Name();

    /**
     * The meta object literal for the '<em><b>Panes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__PANES = eINSTANCE.getApplication_Panes();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.PaneImpl <em>Pane</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.PaneImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getPane()
     * @generated
     */
    EClass PANE = eINSTANCE.getPane();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANE__NAME = eINSTANCE.getPane_Name();

    /**
     * The meta object literal for the '<em><b>Frames</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PANE__FRAMES = eINSTANCE.getPane_Frames();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.FrameImpl <em>Frame</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.FrameImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getFrame()
     * @generated
     */
    EClass FRAME = eINSTANCE.getFrame();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAME__ELEMENTS = eINSTANCE.getFrame_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ElementsImpl <em>Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ElementsImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getElements()
     * @generated
     */
    EClass ELEMENTS = eINSTANCE.getElements();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENTS__TEXT = eINSTANCE.getElements_Text();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENTS__CONSTRAINT = eINSTANCE.getElements_Constraint();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.TextImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ButtonImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ConstraintImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintTypeVerticalImpl <em>Constraint Type Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ConstraintTypeVerticalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintTypeVertical()
     * @generated
     */
    EClass CONSTRAINT_TYPE_VERTICAL = eINSTANCE.getConstraintTypeVertical();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintTypeHorizontalImpl <em>Constraint Type Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ConstraintTypeHorizontalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintTypeHorizontal()
     * @generated
     */
    EClass CONSTRAINT_TYPE_HORIZONTAL = eINSTANCE.getConstraintTypeHorizontal();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintParameterVerticalImpl <em>Constraint Parameter Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ConstraintParameterVerticalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintParameterVertical()
     * @generated
     */
    EClass CONSTRAINT_PARAMETER_VERTICAL = eINSTANCE.getConstraintParameterVertical();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.ConstraintParameterHorizontalImpl <em>Constraint Parameter Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.ConstraintParameterHorizontalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getConstraintParameterHorizontal()
     * @generated
     */
    EClass CONSTRAINT_PARAMETER_HORIZONTAL = eINSTANCE.getConstraintParameterHorizontal();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.VerticalImpl <em>Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.VerticalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getVertical()
     * @generated
     */
    EClass VERTICAL = eINSTANCE.getVertical();

    /**
     * The meta object literal for the '<em><b>Constraint Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTICAL__CONSTRAINT_TYPE = eINSTANCE.getVertical_ConstraintType();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTICAL__PARAM = eINSTANCE.getVertical_Param();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.HorizontalImpl <em>Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.HorizontalImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getHorizontal()
     * @generated
     */
    EClass HORIZONTAL = eINSTANCE.getHorizontal();

    /**
     * The meta object literal for the '<em><b>Constraint Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HORIZONTAL__CONSTRAINT_TYPE = eINSTANCE.getHorizontal_ConstraintType();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HORIZONTAL__PARAM = eINSTANCE.getHorizontal_Param();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.RightOfImpl <em>Right Of</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.RightOfImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getRightOf()
     * @generated
     */
    EClass RIGHT_OF = eINSTANCE.getRightOf();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.LeftOfImpl <em>Left Of</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.LeftOfImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getLeftOf()
     * @generated
     */
    EClass LEFT_OF = eINSTANCE.getLeftOf();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.BottomOfImpl <em>Bottom Of</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.BottomOfImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getBottomOf()
     * @generated
     */
    EClass BOTTOM_OF = eINSTANCE.getBottomOf();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.TopOfImpl <em>Top Of</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.TopOfImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getTopOf()
     * @generated
     */
    EClass TOP_OF = eINSTANCE.getTopOf();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.PersentageImpl <em>Persentage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.PersentageImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getPersentage()
     * @generated
     */
    EClass PERSENTAGE = eINSTANCE.getPersentage();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSENTAGE__VALUE = eINSTANCE.getPersentage_Value();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.RightImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.LeftImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.MiddleImpl <em>Middle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.MiddleImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getMiddle()
     * @generated
     */
    EClass MIDDLE = eINSTANCE.getMiddle();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.TopImpl <em>Top</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.TopImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getTop()
     * @generated
     */
    EClass TOP = eINSTANCE.getTop();

    /**
     * The meta object literal for the '{@link org.xtext.niste15.mdsd.android.impl.BottomImpl <em>Bottom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.niste15.mdsd.android.impl.BottomImpl
     * @see org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl#getBottom()
     * @generated
     */
    EClass BOTTOM = eINSTANCE.getBottom();

  }

} //AndroidPackage
