/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.Application#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.Application#getPanes <em>Panes</em>}</li>
 * </ul>
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getApplication()
 * @model
 * @generated
 */
public interface Application extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getApplication_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Application#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Panes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.niste15.mdsd.android.Pane}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Panes</em>' containment reference list.
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getApplication_Panes()
   * @model containment="true"
   * @generated
   */
  EList<Pane> getPanes();

} // Application
