/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getConstraintType()
 * @model
 * @generated
 */
public interface ConstraintType extends EObject
{
} // ConstraintType
