/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Type Horizontal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getConstraintTypeHorizontal()
 * @model
 * @generated
 */
public interface ConstraintTypeHorizontal extends EObject
{
} // ConstraintTypeHorizontal
