/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.Frame#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.Frame#getElements <em>Elements</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.Frame#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getFrame()
 * @model
 * @generated
 */
public interface Frame extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getFrame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Frame#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.niste15.mdsd.android.Elements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getFrame_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Elements> getElements();

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(Constraint)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getFrame_Constraint()
   * @model containment="true"
   * @generated
   */
  Constraint getConstraint();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Frame#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(Constraint value);

} // Frame
