/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Horizontal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.Horizontal#getConstraintType <em>Constraint Type</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.Horizontal#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getHorizontal()
 * @model
 * @generated
 */
public interface Horizontal extends Constraint
{
  /**
   * Returns the value of the '<em><b>Constraint Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Type</em>' containment reference.
   * @see #setConstraintType(ConstraintTypeHorizontal)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getHorizontal_ConstraintType()
   * @model containment="true"
   * @generated
   */
  ConstraintTypeHorizontal getConstraintType();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Horizontal#getConstraintType <em>Constraint Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Type</em>' containment reference.
   * @see #getConstraintType()
   * @generated
   */
  void setConstraintType(ConstraintTypeHorizontal value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(ConstraintParameterHorizontal)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getHorizontal_Param()
   * @model containment="true"
   * @generated
   */
  ConstraintParameterHorizontal getParam();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Horizontal#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ConstraintParameterHorizontal value);

} // Horizontal
