/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right Of</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getRightOf()
 * @model
 * @generated
 */
public interface RightOf extends ConstraintTypeVertical
{
} // RightOf
