/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.Text#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getText()
 * @model
 * @generated
 */
public interface Text extends Elements
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(TextContent)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getText_Text()
   * @model containment="true"
   * @generated
   */
  TextContent getText();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Text#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(TextContent value);

} // Text
