/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getTop()
 * @model
 * @generated
 */
public interface Top extends ConstraintParameter
{
} // Top
