/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertical</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.Vertical#getConstraintType <em>Constraint Type</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.Vertical#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see org.xtext.niste15.mdsd.android.AndroidPackage#getVertical()
 * @model
 * @generated
 */
public interface Vertical extends Constraint
{
  /**
   * Returns the value of the '<em><b>Constraint Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Type</em>' containment reference.
   * @see #setConstraintType(ConstraintTypeVertical)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getVertical_ConstraintType()
   * @model containment="true"
   * @generated
   */
  ConstraintTypeVertical getConstraintType();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Vertical#getConstraintType <em>Constraint Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Type</em>' containment reference.
   * @see #getConstraintType()
   * @generated
   */
  void setConstraintType(ConstraintTypeVertical value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(ConstraintParameterVertical)
   * @see org.xtext.niste15.mdsd.android.AndroidPackage#getVertical_Param()
   * @model containment="true"
   * @generated
   */
  ConstraintParameterVertical getParam();

  /**
   * Sets the value of the '{@link org.xtext.niste15.mdsd.android.Vertical#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ConstraintParameterVertical value);

} // Vertical
