/*
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AndroidUiModule extends AbstractAndroidUiModule {

	public AndroidUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
