/*
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AndroidGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Model");
		private final Assignment cApplicationAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cApplicationApplicationParserRuleCall_0 = (RuleCall)cApplicationAssignment.eContents().get(0);
		
		//Model:
		//	application+=Application*;
		@Override public ParserRule getRule() { return rule; }
		
		//application+=Application*
		public Assignment getApplicationAssignment() { return cApplicationAssignment; }
		
		//Application
		public RuleCall getApplicationApplicationParserRuleCall_0() { return cApplicationApplicationParserRuleCall_0; }
	}
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPanesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPanesPaneParserRuleCall_3_0 = (RuleCall)cPanesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Application:
		//	'Application' name=ID '{' panes+=Pane '}' //NavigationBar
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Application' name=ID '{' panes+=Pane '}'
		public Group getGroup() { return cGroup; }
		
		//'Application'
		public Keyword getApplicationKeyword_0() { return cApplicationKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//panes+=Pane
		public Assignment getPanesAssignment_3() { return cPanesAssignment_3; }
		
		//Pane
		public RuleCall getPanesPaneParserRuleCall_3_0() { return cPanesPaneParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PaneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Pane");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPaneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFramesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFramesFrameParserRuleCall_3_0 = (RuleCall)cFramesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Pane:
		//	'Pane' name=ID '{' frames+=Frame '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Pane' name=ID '{' frames+=Frame '}'
		public Group getGroup() { return cGroup; }
		
		//'Pane'
		public Keyword getPaneKeyword_0() { return cPaneKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//frames+=Frame
		public Assignment getFramesAssignment_3() { return cFramesAssignment_3; }
		
		//Frame
		public RuleCall getFramesFrameParserRuleCall_3_0() { return cFramesFrameParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FrameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Frame");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFrameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsElementsParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Frame:
		//	'Frame' '{' elements+=Elements '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Frame' '{' elements+=Elements '}'
		public Group getGroup() { return cGroup; }
		
		//'Frame'
		public Keyword getFrameKeyword_0() { return cFrameKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//elements+=Elements
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//Elements
		public RuleCall getElementsElementsParserRuleCall_2_0() { return cElementsElementsParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ElementsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Elements");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cButtonParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTextParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Elements:
		//	Button | Text // ADD MORE 
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Button | Text
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Button
		public RuleCall getButtonParserRuleCall_0() { return cButtonParserRuleCall_0; }
		
		//Text
		public RuleCall getTextParserRuleCall_1() { return cTextParserRuleCall_1; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Assignment cConstraintAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConstraintConstraintParserRuleCall_3_0 = (RuleCall)cConstraintAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Text:
		//	'Text' '(' text=STRING constraint=Constraint ')' //More Params
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Text' '(' text=STRING constraint=Constraint ')'
		public Group getGroup() { return cGroup; }
		
		//'Text'
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
		
		//constraint=Constraint
		public Assignment getConstraintAssignment_3() { return cConstraintAssignment_3; }
		
		//Constraint
		public RuleCall getConstraintConstraintParserRuleCall_3_0() { return cConstraintConstraintParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Button");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Assignment cConstraintAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConstraintConstraintParserRuleCall_3_0 = (RuleCall)cConstraintAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Button:
		//	'Button' '(' text=STRING constraint=Constraint ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'Button' '(' text=STRING constraint=Constraint ')'
		public Group getGroup() { return cGroup; }
		
		//'Button'
		public Keyword getButtonKeyword_0() { return cButtonKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
		
		//constraint=Constraint
		public Assignment getConstraintAssignment_3() { return cConstraintAssignment_3; }
		
		//Constraint
		public RuleCall getConstraintConstraintParserRuleCall_3_0() { return cConstraintConstraintParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.Constraint");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cVerticalAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cConstraintsVerticalKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Keyword cColonKeyword_0_2_0 = (Keyword)cGroup_0_2.eContents().get(0);
		private final Assignment cConstraintTypeAssignment_0_2_1 = (Assignment)cGroup_0_2.eContents().get(1);
		private final RuleCall cConstraintTypeConstraintTypeVerticalParserRuleCall_0_2_1_0 = (RuleCall)cConstraintTypeAssignment_0_2_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cParamAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cParamConstraintParameterVerticalParserRuleCall_0_4_0 = (RuleCall)cParamAssignment_0_4.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cHorizontalAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cConstraintsHorizontalKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cColonKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cConstraintTypeAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cConstraintTypeConstraintTypeHorizontalParserRuleCall_1_2_1_0 = (RuleCall)cConstraintTypeAssignment_1_2_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cParamAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cParamConstraintParameterHorizontalParserRuleCall_1_4_0 = (RuleCall)cParamAssignment_1_4.eContents().get(0);
		
		//Constraint:
		//	{Vertical} 'constraintsVertical' (':' constraintType=ConstraintTypeVertical) '=' param=ConstraintParameterVertical |
		//	{Horizontal} 'constraintsHorizontal' (':' constraintType=ConstraintTypeHorizontal) '='
		//	param=ConstraintParameterHorizontal;
		@Override public ParserRule getRule() { return rule; }
		
		//{Vertical} 'constraintsVertical' (':' constraintType=ConstraintTypeVertical) '=' param=ConstraintParameterVertical |
		//{Horizontal} 'constraintsHorizontal' (':' constraintType=ConstraintTypeHorizontal) '='
		//param=ConstraintParameterHorizontal
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Vertical} 'constraintsVertical' (':' constraintType=ConstraintTypeVertical) '=' param=ConstraintParameterVertical
		public Group getGroup_0() { return cGroup_0; }
		
		//{Vertical}
		public Action getVerticalAction_0_0() { return cVerticalAction_0_0; }
		
		//'constraintsVertical'
		public Keyword getConstraintsVerticalKeyword_0_1() { return cConstraintsVerticalKeyword_0_1; }
		
		//(':' constraintType=ConstraintTypeVertical)
		public Group getGroup_0_2() { return cGroup_0_2; }
		
		//':'
		public Keyword getColonKeyword_0_2_0() { return cColonKeyword_0_2_0; }
		
		//constraintType=ConstraintTypeVertical
		public Assignment getConstraintTypeAssignment_0_2_1() { return cConstraintTypeAssignment_0_2_1; }
		
		//ConstraintTypeVertical
		public RuleCall getConstraintTypeConstraintTypeVerticalParserRuleCall_0_2_1_0() { return cConstraintTypeConstraintTypeVerticalParserRuleCall_0_2_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_0_3() { return cEqualsSignKeyword_0_3; }
		
		//param=ConstraintParameterVertical
		public Assignment getParamAssignment_0_4() { return cParamAssignment_0_4; }
		
		//ConstraintParameterVertical
		public RuleCall getParamConstraintParameterVerticalParserRuleCall_0_4_0() { return cParamConstraintParameterVerticalParserRuleCall_0_4_0; }
		
		//{Horizontal} 'constraintsHorizontal' (':' constraintType=ConstraintTypeHorizontal) '='
		//param=ConstraintParameterHorizontal
		public Group getGroup_1() { return cGroup_1; }
		
		//{Horizontal}
		public Action getHorizontalAction_1_0() { return cHorizontalAction_1_0; }
		
		//'constraintsHorizontal'
		public Keyword getConstraintsHorizontalKeyword_1_1() { return cConstraintsHorizontalKeyword_1_1; }
		
		//(':' constraintType=ConstraintTypeHorizontal)
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//':'
		public Keyword getColonKeyword_1_2_0() { return cColonKeyword_1_2_0; }
		
		//constraintType=ConstraintTypeHorizontal
		public Assignment getConstraintTypeAssignment_1_2_1() { return cConstraintTypeAssignment_1_2_1; }
		
		//ConstraintTypeHorizontal
		public RuleCall getConstraintTypeConstraintTypeHorizontalParserRuleCall_1_2_1_0() { return cConstraintTypeConstraintTypeHorizontalParserRuleCall_1_2_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_3() { return cEqualsSignKeyword_1_3; }
		
		//param=ConstraintParameterHorizontal
		public Assignment getParamAssignment_1_4() { return cParamAssignment_1_4; }
		
		//ConstraintParameterHorizontal
		public RuleCall getParamConstraintParameterHorizontalParserRuleCall_1_4_0() { return cParamConstraintParameterHorizontalParserRuleCall_1_4_0; }
	}
	public class ConstraintTypeVerticalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.ConstraintTypeVertical");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cRightOfAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cRightOfKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cLeftOfAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLeftOfKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//ConstraintTypeVertical:
		//	{RightOf} 'rightOf' | {LeftOf} 'leftOf';
		@Override public ParserRule getRule() { return rule; }
		
		//{RightOf} 'rightOf' | {LeftOf} 'leftOf'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{RightOf} 'rightOf'
		public Group getGroup_0() { return cGroup_0; }
		
		//{RightOf}
		public Action getRightOfAction_0_0() { return cRightOfAction_0_0; }
		
		//'rightOf'
		public Keyword getRightOfKeyword_0_1() { return cRightOfKeyword_0_1; }
		
		//{LeftOf} 'leftOf'
		public Group getGroup_1() { return cGroup_1; }
		
		//{LeftOf}
		public Action getLeftOfAction_1_0() { return cLeftOfAction_1_0; }
		
		//'leftOf'
		public Keyword getLeftOfKeyword_1_1() { return cLeftOfKeyword_1_1; }
	}
	public class ConstraintTypeHorizontalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.ConstraintTypeHorizontal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBottomOfAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cBottomOfKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cTopOfAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cTopOfKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//ConstraintTypeHorizontal:
		//	{BottomOf} 'bottomOf' | {TopOf} 'topOf';
		@Override public ParserRule getRule() { return rule; }
		
		//{BottomOf} 'bottomOf' | {TopOf} 'topOf'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{BottomOf} 'bottomOf'
		public Group getGroup_0() { return cGroup_0; }
		
		//{BottomOf}
		public Action getBottomOfAction_0_0() { return cBottomOfAction_0_0; }
		
		//'bottomOf'
		public Keyword getBottomOfKeyword_0_1() { return cBottomOfKeyword_0_1; }
		
		//{TopOf} 'topOf'
		public Group getGroup_1() { return cGroup_1; }
		
		//{TopOf}
		public Action getTopOfAction_1_0() { return cTopOfAction_1_0; }
		
		//'topOf'
		public Keyword getTopOfKeyword_1_1() { return cTopOfKeyword_1_1; }
	}
	public class ConstraintParameterVerticalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.ConstraintParameterVertical");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPersentageAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cRightAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cRightKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cLeftAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cLeftKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cMiddleAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cMiddleKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		
		//ConstraintParameterVertical:
		//	{Persentage} value=ID '%' | {Right} 'right' | {Left} 'left' | {Middle} 'middle';
		@Override public ParserRule getRule() { return rule; }
		
		//{Persentage} value=ID '%' | {Right} 'right' | {Left} 'left' | {Middle} 'middle'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Persentage} value=ID '%'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Persentage}
		public Action getPersentageAction_0_0() { return cPersentageAction_0_0; }
		
		//value=ID
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_0_1_0() { return cValueIDTerminalRuleCall_0_1_0; }
		
		//'%'
		public Keyword getPercentSignKeyword_0_2() { return cPercentSignKeyword_0_2; }
		
		//{Right} 'right'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Right}
		public Action getRightAction_1_0() { return cRightAction_1_0; }
		
		//'right'
		public Keyword getRightKeyword_1_1() { return cRightKeyword_1_1; }
		
		//{Left} 'left'
		public Group getGroup_2() { return cGroup_2; }
		
		//{Left}
		public Action getLeftAction_2_0() { return cLeftAction_2_0; }
		
		//'left'
		public Keyword getLeftKeyword_2_1() { return cLeftKeyword_2_1; }
		
		//{Middle} 'middle'
		public Group getGroup_3() { return cGroup_3; }
		
		//{Middle}
		public Action getMiddleAction_3_0() { return cMiddleAction_3_0; }
		
		//'middle'
		public Keyword getMiddleKeyword_3_1() { return cMiddleKeyword_3_1; }
	}
	public class ConstraintParameterHorizontalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.niste15.mdsd.Android.ConstraintParameterHorizontal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPersentageAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cTopAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cTopKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cBottomAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cBottomKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cMiddleAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cMiddleKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		
		//ConstraintParameterHorizontal:
		//	{Persentage} value=ID '%' | {Top} 'top' | {Bottom} 'bottom' | {Middle} 'middle';
		@Override public ParserRule getRule() { return rule; }
		
		//{Persentage} value=ID '%' | {Top} 'top' | {Bottom} 'bottom' | {Middle} 'middle'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Persentage} value=ID '%'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Persentage}
		public Action getPersentageAction_0_0() { return cPersentageAction_0_0; }
		
		//value=ID
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_0_1_0() { return cValueIDTerminalRuleCall_0_1_0; }
		
		//'%'
		public Keyword getPercentSignKeyword_0_2() { return cPercentSignKeyword_0_2; }
		
		//{Top} 'top'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Top}
		public Action getTopAction_1_0() { return cTopAction_1_0; }
		
		//'top'
		public Keyword getTopKeyword_1_1() { return cTopKeyword_1_1; }
		
		//{Bottom} 'bottom'
		public Group getGroup_2() { return cGroup_2; }
		
		//{Bottom}
		public Action getBottomAction_2_0() { return cBottomAction_2_0; }
		
		//'bottom'
		public Keyword getBottomKeyword_2_1() { return cBottomKeyword_2_1; }
		
		//{Middle} 'middle'
		public Group getGroup_3() { return cGroup_3; }
		
		//{Middle}
		public Action getMiddleAction_3_0() { return cMiddleAction_3_0; }
		
		//'middle'
		public Keyword getMiddleKeyword_3_1() { return cMiddleKeyword_3_1; }
	}
	
	
	private final ModelElements pModel;
	private final ApplicationElements pApplication;
	private final PaneElements pPane;
	private final FrameElements pFrame;
	private final ElementsElements pElements;
	private final TextElements pText;
	private final ButtonElements pButton;
	private final ConstraintElements pConstraint;
	private final ConstraintTypeVerticalElements pConstraintTypeVertical;
	private final ConstraintTypeHorizontalElements pConstraintTypeHorizontal;
	private final ConstraintParameterVerticalElements pConstraintParameterVertical;
	private final ConstraintParameterHorizontalElements pConstraintParameterHorizontal;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AndroidGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pApplication = new ApplicationElements();
		this.pPane = new PaneElements();
		this.pFrame = new FrameElements();
		this.pElements = new ElementsElements();
		this.pText = new TextElements();
		this.pButton = new ButtonElements();
		this.pConstraint = new ConstraintElements();
		this.pConstraintTypeVertical = new ConstraintTypeVerticalElements();
		this.pConstraintTypeHorizontal = new ConstraintTypeHorizontalElements();
		this.pConstraintParameterVertical = new ConstraintParameterVerticalElements();
		this.pConstraintParameterHorizontal = new ConstraintParameterHorizontalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.niste15.mdsd.Android".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	application+=Application*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Application:
	//	'Application' name=ID '{' panes+=Pane '}' //NavigationBar
	//;
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//Pane:
	//	'Pane' name=ID '{' frames+=Frame '}';
	public PaneElements getPaneAccess() {
		return pPane;
	}
	
	public ParserRule getPaneRule() {
		return getPaneAccess().getRule();
	}
	
	//Frame:
	//	'Frame' '{' elements+=Elements '}';
	public FrameElements getFrameAccess() {
		return pFrame;
	}
	
	public ParserRule getFrameRule() {
		return getFrameAccess().getRule();
	}
	
	//Elements:
	//	Button | Text // ADD MORE 
	//;
	public ElementsElements getElementsAccess() {
		return pElements;
	}
	
	public ParserRule getElementsRule() {
		return getElementsAccess().getRule();
	}
	
	//Text:
	//	'Text' '(' text=STRING constraint=Constraint ')' //More Params
	//;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Button:
	//	'Button' '(' text=STRING constraint=Constraint ')';
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}
	
	//Constraint:
	//	{Vertical} 'constraintsVertical' (':' constraintType=ConstraintTypeVertical) '=' param=ConstraintParameterVertical |
	//	{Horizontal} 'constraintsHorizontal' (':' constraintType=ConstraintTypeHorizontal) '='
	//	param=ConstraintParameterHorizontal;
	public ConstraintElements getConstraintAccess() {
		return pConstraint;
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}
	
	//ConstraintTypeVertical:
	//	{RightOf} 'rightOf' | {LeftOf} 'leftOf';
	public ConstraintTypeVerticalElements getConstraintTypeVerticalAccess() {
		return pConstraintTypeVertical;
	}
	
	public ParserRule getConstraintTypeVerticalRule() {
		return getConstraintTypeVerticalAccess().getRule();
	}
	
	//ConstraintTypeHorizontal:
	//	{BottomOf} 'bottomOf' | {TopOf} 'topOf';
	public ConstraintTypeHorizontalElements getConstraintTypeHorizontalAccess() {
		return pConstraintTypeHorizontal;
	}
	
	public ParserRule getConstraintTypeHorizontalRule() {
		return getConstraintTypeHorizontalAccess().getRule();
	}
	
	//ConstraintParameterVertical:
	//	{Persentage} value=ID '%' | {Right} 'right' | {Left} 'left' | {Middle} 'middle';
	public ConstraintParameterVerticalElements getConstraintParameterVerticalAccess() {
		return pConstraintParameterVertical;
	}
	
	public ParserRule getConstraintParameterVerticalRule() {
		return getConstraintParameterVerticalAccess().getRule();
	}
	
	//ConstraintParameterHorizontal:
	//	{Persentage} value=ID '%' | {Top} 'top' | {Bottom} 'bottom' | {Middle} 'middle';
	public ConstraintParameterHorizontalElements getConstraintParameterHorizontalAccess() {
		return pConstraintParameterHorizontal;
	}
	
	public ParserRule getConstraintParameterHorizontalRule() {
		return getConstraintParameterHorizontalAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
