/*
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.niste15.mdsd.parser.antlr.internal.InternalAndroidParser;
import org.xtext.niste15.mdsd.services.AndroidGrammarAccess;

public class AndroidParser extends AbstractAntlrParser {

	@Inject
	private AndroidGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAndroidParser createParser(XtextTokenStream stream) {
		return new InternalAndroidParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AndroidGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AndroidGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
