/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.BottomOf;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bottom Of</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BottomOfImpl extends ConstraintTypeHorizontalImpl implements BottomOf
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BottomOfImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidPackage.Literals.BOTTOM_OF;
  }

} //BottomOfImpl
