/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.ConstraintParameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constraint Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConstraintParameterImpl extends MinimalEObjectImpl.Container implements ConstraintParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstraintParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidPackage.Literals.CONSTRAINT_PARAMETER;
  }

} //ConstraintParameterImpl
