/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.ConstraintParameterHorizontal;
import org.xtext.niste15.mdsd.android.ConstraintTypeHorizontal;
import org.xtext.niste15.mdsd.android.Horizontal;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Horizontal</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.niste15.mdsd.android.impl.HorizontalImpl#getConstraintType <em>Constraint Type</em>}</li>
 *   <li>{@link org.xtext.niste15.mdsd.android.impl.HorizontalImpl#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HorizontalImpl extends ConstraintImpl implements Horizontal
{
  /**
   * The cached value of the '{@link #getConstraintType() <em>Constraint Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstraintType()
   * @generated
   * @ordered
   */
  protected ConstraintTypeHorizontal constraintType;

  /**
   * The cached value of the '{@link #getParam() <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParam()
   * @generated
   * @ordered
   */
  protected ConstraintParameterHorizontal param;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HorizontalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidPackage.Literals.HORIZONTAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintTypeHorizontal getConstraintType()
  {
    return constraintType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConstraintType(ConstraintTypeHorizontal newConstraintType, NotificationChain msgs)
  {
    ConstraintTypeHorizontal oldConstraintType = constraintType;
    constraintType = newConstraintType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE, oldConstraintType, newConstraintType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConstraintType(ConstraintTypeHorizontal newConstraintType)
  {
    if (newConstraintType != constraintType)
    {
      NotificationChain msgs = null;
      if (constraintType != null)
        msgs = ((InternalEObject)constraintType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE, null, msgs);
      if (newConstraintType != null)
        msgs = ((InternalEObject)newConstraintType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE, null, msgs);
      msgs = basicSetConstraintType(newConstraintType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE, newConstraintType, newConstraintType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintParameterHorizontal getParam()
  {
    return param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParam(ConstraintParameterHorizontal newParam, NotificationChain msgs)
  {
    ConstraintParameterHorizontal oldParam = param;
    param = newParam;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AndroidPackage.HORIZONTAL__PARAM, oldParam, newParam);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParam(ConstraintParameterHorizontal newParam)
  {
    if (newParam != param)
    {
      NotificationChain msgs = null;
      if (param != null)
        msgs = ((InternalEObject)param).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AndroidPackage.HORIZONTAL__PARAM, null, msgs);
      if (newParam != null)
        msgs = ((InternalEObject)newParam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AndroidPackage.HORIZONTAL__PARAM, null, msgs);
      msgs = basicSetParam(newParam, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AndroidPackage.HORIZONTAL__PARAM, newParam, newParam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE:
        return basicSetConstraintType(null, msgs);
      case AndroidPackage.HORIZONTAL__PARAM:
        return basicSetParam(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE:
        return getConstraintType();
      case AndroidPackage.HORIZONTAL__PARAM:
        return getParam();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE:
        setConstraintType((ConstraintTypeHorizontal)newValue);
        return;
      case AndroidPackage.HORIZONTAL__PARAM:
        setParam((ConstraintParameterHorizontal)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE:
        setConstraintType((ConstraintTypeHorizontal)null);
        return;
      case AndroidPackage.HORIZONTAL__PARAM:
        setParam((ConstraintParameterHorizontal)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AndroidPackage.HORIZONTAL__CONSTRAINT_TYPE:
        return constraintType != null;
      case AndroidPackage.HORIZONTAL__PARAM:
        return param != null;
    }
    return super.eIsSet(featureID);
  }

} //HorizontalImpl
