/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.LeftOf;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Left Of</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LeftOfImpl extends ConstraintTypeImpl implements LeftOf
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LeftOfImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidPackage.Literals.LEFT_OF;
  }

} //LeftOfImpl
