/**
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.android.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.Top;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Top</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TopImpl extends ConstraintParameterImpl implements Top
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TopImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AndroidPackage.Literals.TOP;
  }

} //TopImpl
