/*
 * generated by Xtext 2.22.0
 */
package org.xtext.niste15.mdsd.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.niste15.mdsd.android.AndroidPackage;
import org.xtext.niste15.mdsd.android.Button;
import org.xtext.niste15.mdsd.android.Pane;
import org.xtext.niste15.mdsd.android.Text;
import org.xtext.niste15.mdsd.android.impl.AndroidPackageImpl;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class AndroidValidator extends AbstractAndroidValidator {
	
	public static final String INVALID_NAME = "invalidName";
	public static final String NO_NAVIGATION = "noButtonNavigation";

	@Check
	public void checkTextNameIsNotEmpty(Text text) {
		if (text.getText().getText().isEmpty()) {
			warning("Text should not be empty", AndroidPackage.Literals.TEXT__TEXT, INVALID_NAME);
		}
	}
	
	@Check
	public void checkIfButtonHasNoNavigation(Button button) {
		if (button.getPane() == null) {
			warning("Without navigation, the button has no function", AndroidPackage.Literals.BUTTON__PANE, NO_NAVIGATION);
		}
	}
	
}
